server.port=8084

spring.application.name=notification-service

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:55432/campusenroll}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:campus}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:campus123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=campusenroll

spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:campus}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:campus123}

spring.data.redis.host=${SPRING_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_REDIS_PORT:6379}

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
